# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               isilib
tagline:             'A Python library for simplifying bibliometric research of Web of Science data'
description:         'Reid McIlroy-Young and John McLevey'
url:                 www.networkslab.org
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              KI Networks Lab
  url:               https://twitter.com/johnmclevey
  email:             john.mclevey@uwaterloo.ca

# Custom vars
version:             1.0.0
