# Site wide configuration

title: metaknowledge
locale: en_US
description: A Python3 package for social networks and bibliometric research on knowledge
logo: site-logo.png
search: true
url: http://networkslab.org
baseurl: /metaknowledge

# Jekyll configuration

permalink: /:categories/:title
#relative_permalinks: true

markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: John McLevey and Reid McIlroy-Young
  avatar: bio-photo.jpg
  email: john.mclevey@uwaterloo.ca
  disqus-shortname:
  twitter: #johnmclevey
  facebook: #username
  github: #mclevey
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics: UA-25394214-5
    verify:
    ad-client:
    ad-slot:
  bing-verify:
